---
title: "Diseños experimentales"
author: "Jheferson Vasquez Guevara"
format: html
editor: visual
---

# Diseños experimentales
```{r}
library(agricolae)

```

## DCA
Factor - dosis de fertilización nitrogenada (kg/ha)
0 - testigo
50
100
diseño : DCA
Repeticiones : 5
UE - 3 dosis x 5 rep = 15

```{r}
# Diseño Completamente al Azar (DCA)
library(agricolae)

# Factor: dosis de fertilización nitrogenada (kg/ha)
tratamientos <- c("0", "50", "100")   # 0 = testigo
rep <- 5                              # número de repeticiones

# Generar el diseño DCA
diseño_dca <- design.crd(tratamientos, r = rep, seed = 123, serie = 2)

# Mostrar el diseño experimental
diseño_dca$book
```

```{r}
View(diseño_dca$book)
```

## DBCA
Factor 1 - dosis de fertilización nitrogenada (kg/ha)
factor 2 - cultivares de papa
peruanita
canchan
diseño : DBCA
Repeticiones : 4
UE - 3 dosis x 2 cultivares x 4 rep = 24

```{r}
trt<- c(3,2) # factorial 3x2
outdesing <- design.ab(trt, r =3, serie =2)
book <- outdesing$book
book

```

